etfs:
  - SPY
  - QQQ
  - IEF
  - GLD
  - EEM
  - VNQ
  - AMXL.MX
  - WALMEX.MX
  - BIMBOA.MX
  - CEMEXCPO.MX
  - GFNORTEO.MX
start_date: "2015-01-01"
prediction_horizon: 5
risk_free_rate: 0.015
data_dir: "data"
model_dir: "models"
evaluation_dir: "results/metrics"
target_cols:
  SPY: Close
  QQQ: Close
  IEF: Close
  GLD: Close
  EEM: Close
  VNQ: Close
  AMXL.MX: Close
  WALMEX.MX: Close
  BIMBOA.MX: Close
  CEMEXCPO.MX: Close
  GFNORTEO.MX: Close
