name: Cleanup Models
permissions:
  contents: write
on:
  workflow_dispatch: {}

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install yfinance==0.2.61 ta==0.11.0 requests-cache==1.2.0 pandas>=2.2
          pip install -r requirements.txt
      - run: python -m src.clean_models
      - name: Commit removed models
        env:
          PUSH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A models/
          if git diff --cached --quiet; then
            echo "No model changes to commit"
          else
            git commit -m "Remove stored models"
            token=${PUSH_TOKEN:-$GITHUB_TOKEN}
            git push https://x-access-token:${token}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi
