name: Daily Processing
permissions:
  contents: write
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}
jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: python -m src.abt.build_abt
      - run: python -m src.predict
      - name: Commit results
        env:
          PUSH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add results/predictions.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update daily predictions"
            token=${PUSH_TOKEN:-$GITHUB_TOKEN}
            git push https://x-access-token:${token}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi
      - run: python -m src.notify.notifier --message "Proceso diario completado"
