name: Monthly Training
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: python -m src.training
      - run: python -m src.predict
      - run: python -m src.portfolio.optimize
      - run: python -m src.notify.notifier --message "Proceso mensual completado"
